In [1]:
#programming_fever
#image bluring
import cv2 
import numpy as np 
  
imag = cv2.imread('E://OpenCV//programming_fever_.logo.jpg') 
image = cv2.resize(imag, (0, 0), fx =0.1, fy =0.1)  

blur_filter1 = np.ones((3, 3), np.float)/(9.0) 
  
blur_filter2 = np.ones((5, 5), np.float)/(25.0) 
  
blur_filter3 = np.ones((7, 7), np.float)/(49.0) 
  
image_blur1 = cv2.filter2D(image, -1, blur_filter1) 
image_blur2 = cv2.filter2D(image, -1, blur_filter2) 
image_blur3 = cv2.filter2D(image, -1, blur_filter3) 
print(image) 
print(type(image))
cv2.imshow('programming_fever.logo.ORIGINAL', image) 
cv2.imshow('programming_fever.logo.BLUR1', image_blur1) 
cv2.imshow('programming_fever.logo.BLUR2', image_blur2) 
cv2.imshow('programming_fever.logo.BLUR3', image_blur3) 
  
cv2.waitKey(0) 
cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
<class 'numpy.ndarray'>
