# QR code Scanner

In [ ]:
#programming_fever
import cv2
import numpy as np
import sys
import time

inputImage = cv2.imread("D://OpenCV//opencv jupyter files//programming_fever.png")
# Display barcode and QR code location
def display(im, bbox):
    n = len(bbox)
    for j in range(n):
        cv2.line(im, tuple(bbox[j][0]), tuple(bbox[ (j+1) % n][0]), (255,0,0), 3)

    # Display results
    cv2.imshow("Results", im)
    
qrDecoder = cv2.QRCodeDetector()
# Detect and decode the qrcode
data,bbox,rectifiedImage = qrDecoder.detectAndDecode(inputImage)
if len(data)>0:
    print("Decoded Data : {}".format(data))
    display(inputImage, bbox)
    rectifiedImage = np.uint8(rectifiedImage)
    cv2.imshow("Rectified QRCode", rectifiedImage)

else:
    print("QR Code not detected")
    cv2.imshow("Results", inputImage)

cv2.waitKey(0)
cv2.destroyAllWindows()



Decoded Data : https://www.instagram.com/programming_fever/
[[[ 40.  40.]]

 [[369.  40.]]

 [[369. 369.]]

 [[ 40. 369.]]]


FB Page
<a href="https://www.facebook.com/GeekyPRAVEE">@programmimg_fever</a>

GitHub link
<a href="https://github.com/GeekyPRAVEE">@programmimg_fever</a>

Twitter 
<a href="https://twitter.com/GeekyPRAVEE">@programmimg_fever</a>